
# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'


orbs:
  node: circleci/node@4.1

  slack: circleci/slack@4.4.4

workflows:
  sample:
    jobs:
      - node/test:
          version: '15.1'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1,
  slack: circleci/slack@4.4.4
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - slack/notify:
          branch_pattern: main 
          channel: "todoistchallenge" 

workflows:
  example-workflow:
    jobs:
      - example-job

